### ISSUE TITLE
Parameters to service methods which are attributes on a complex type don't appear in soap request

### ISSUE THREAD

**Issue by mcordes** [mvantellingen/python-zeep#125]
Hello, 

I'm making a service call with multiple parameters - some that map to elements and one that maps to an attribute on a complex type. Something like this:

```
zeepClient.service.<service method>(someparam='1', someattribute='2')
```

The resulting soap request includes `someparam` as expected but doesn't include `someattribute`. 

The Complex type associated w/ the request element looks something like the following:  

```
<xsd:complexType name="xyz">
    <xsd:sequence>
        <xsd:element name="someparam" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="someattribute" type="xsd:string"/>
</xsd:complexType>
```

I'm not sure how to give you a test case for this one, but it looks like the last time this worked was release 0.9.0. 

Please let me know if there's anything else I can provide that would help tracking this down.

**Comment by mvantellingen** [comment]
One of the things that is changed is that when attribute names conflict with element names the attribute name is renamed (to attr__<name>). Could you check if the signature in your case is changed?

**Comment by jabhay** [comment]
Hi,

I have the same problem. Note the missing attributes on the request element in the XML below. I show the expected XML below that, as well as the XSD and the corresponding output from python -mzeep, and finally the code I used that's generating the output. The structure I see from printing the requests object looks right, but the XML sent is not correct (as shown).

It's interesting because the requests element has a mix of elements and attributes, but it appears to work fine. It's only the request element that isn't working as I would expect.

Cheers,
Jo

**OUTPUT XML:**
```
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns0="http://ws.namf09.anzlic.org.au" xmlns:ns1="http://namf09.anzlic.org.au" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:execute>
      <ns1:requests id="1.0" version="1.0">
        <ns1:authentication>
          <ns1:username>jabhay</ns1:username>
          <ns1:password>beefcake</ns1:password>
        </ns1:authentication>
        <ns1:features/>
        <ns1:request>
          <ns1:features>
            <ns1:feature name="workflow">
              <ns1:feature name="name">
                <ns1:featureValue>PSMA:baseline_transaction</ns1:featureValue>
              </ns1:feature>
              <ns1:feature name="parameters"/>
            </ns1:feature>
          </ns1:features>
          <ns1:address>
            <ns1:unstructuredAddressLine1>1 broad pl kambah act 2902</ns1:unstructuredAddressLine1>
          </ns1:address>
          <ns1:attributes/>
        </ns1:request>
      </ns1:requests>
    </ns0:execute>
  </soap-env:Body>
</soap-env:Envelope>
```

**EXPECTED:**
```
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns0="http://ws.namf09.anzlic.org.au" xmlns:ns1="http://namf09.anzlic.org.au" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:execute>
      <ns1:requests id="1.0" version="1.0">
        <ns1:authentication>
          <ns1:username>username</ns1:username>
          <ns1:password>password</ns1:password>
        </ns1:authentication>
        <ns1:features/>
        <ns1:request name="executeWorkflow" id="1.0">
          <ns1:features>
            <ns1:feature name="workflow">
              <ns1:feature name="name">
                <ns1:featureValue>PSMA:baseline_transaction</ns1:featureValue>
              </ns1:feature>
              <ns1:feature name="parameters"/>
            </ns1:feature>
          </ns1:features>
          <ns1:address>
            <ns1:unstructuredAddressLine1>1 broad pl kambah act 2902</ns1:unstructuredAddressLine1>
          </ns1:address>
          <ns1:attributes/>
        </ns1:request>
      </ns1:requests>
    </ns0:execute>
  </soap-env:Body>
</soap-env:Envelope>
```
**XSD:**
```
<xs:schema xmlns="http://namf09.anzlic.org.au" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://namf09.anzlic.org.au" version="1.1">
<xs:element name="attributes">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="attribute"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="attribute">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="attributeValue" type="xs:string"/>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="attribute"/>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
<xs:element name="responses">
<xs:annotation>
<xs:documentation>
A Responses Object is the top-level object returned by the NAMF Web Services.
</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" ref="notes"/>
<xs:element name="result">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" ref="attributes"/>
</xs:sequence>
<xs:attribute name="status" type="statusValue" use="required"/>
<xs:attribute name="completed" type="xs:boolean" use="required"/>
<xs:attribute name="hasErrorsInResponseElements" type="xs:boolean" use="required"/>
</xs:complexType>
</xs:element>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="error"/>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="response"/>
</xs:sequence>
<xs:attribute name="id" type="xs:string">
<xs:annotation>
<xs:documentation>The id from the origin</xs:documentation>
</xs:annotation>
</xs:attribute>
</xs:complexType>
</xs:element>
<xs:element name="requests">
<xs:annotation>
<xs:documentation>
A Requests Object is the top-level object set to the NAMF Web Services.
</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element name="authentication">
<xs:complexType>
<xs:sequence>
<xs:element name="username" type="xs:string"/>
<xs:element name="password" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element ref="features"/>
<xs:element minOccurs="0" maxOccurs="unbounded" name="request">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" ref="features"/>
<xs:element minOccurs="0" ref="address"/>
<xs:element minOccurs="0" ref="attributes"/>
</xs:sequence>
<xs:attribute name="id" type="xs:string"/>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="id" type="xs:string"/>
<xs:attribute name="version" type="xs:string"/>
</xs:complexType>
</xs:element>
<xs:element name="features">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="feature"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="feature">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="featureValue" type="xs:string"/>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="feature"/>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
<xs:element name="callVersions">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" name="callVersion">
<xs:complexType>
<xs:sequence>
<xs:element name="description" type="xs:string"/>
<xs:element name="version" type="xs:string"/>
<xs:element minOccurs="0" ref="features"/>
<xs:element minOccurs="0" ref="attributes"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
<xs:element name="address">
<xs:annotation>
<xs:documentation>
The Address Object is based on the AS4590 specification for Address Detail. The structures for managing client currency have been omitted as these are not concerned with addresses but with occupants.
</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="addressIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation>Unique address identifier</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="status" type="addressStatusValue">
<xs:annotation>
<xs:documentation>Address status (AS4590)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexUnitType" type="xs:string">
<xs:annotation>
<xs:documentation>Complex unit type (eg "Unit", "Flat")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexUnitIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation>
Complex unit identifier (including any prefix and/or suffix)
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexLevelType" type="xs:string">
<xs:annotation>
<xs:documentation>Complex level type (eg "Level", "Floor")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexLevelNumber" type="xs:string">
<xs:annotation>
<xs:documentation>
Complex level identifier (including any prefix and/or suffix)
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexStreetNumber1" type="xs:string">
<xs:annotation>
<xs:documentation>
Complex first street number (including any prefix and/or suffix)
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexStreetNumber2" type="xs:string">
<xs:annotation>
<xs:documentation>
Complex second street number (including any prefix and/or suffix)
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexStreetName" type="xs:string">
<xs:annotation>
<xs:documentation>Complex street name</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexStreetType" type="xs:string">
<xs:annotation>
<xs:documentation>Complex street type (eg "AV", "RD", "ST")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="complexStreetSuffix" type="xs:string">
<xs:annotation>
<xs:documentation>Complex street suffix (eg Smith St "West")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="siteName" type="xs:string">
<xs:annotation>
<xs:documentation>Site name (eg building name)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="lotIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation>Lot identifier</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="cadastralIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation>Cadastral identifer (eg "1/34/123456")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="streetNumber1" type="xs:string">
<xs:annotation>
<xs:documentation>
First street number (including any prefix and/or suffix)
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="streetNumber2" type="xs:string">
<xs:annotation>
<xs:documentation>
Second street number (including any prefix and/or suffix)
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="streetName" type="xs:string">
<xs:annotation>
<xs:documentation>Street name</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="streetType" type="xs:string">
<xs:annotation>
<xs:documentation>Street type (eg "AV", "RD", "ST")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="streetSuffix" type="xs:string">
<xs:annotation>
<xs:documentation>Street suffix (eg Smith St "West")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="postalDeliveryTypeCode" type="xs:string">
<xs:annotation>
<xs:documentation>Postal delivery type (eg "PO BOX" 123)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="postalDeliveryIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation>Postal delivery number (eg PO BOX "123")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="localityName" type="xs:string">
<xs:annotation>
<xs:documentation>Locality name (eg Suburb)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="stateTerritory" type="xs:string">
<xs:annotation>
<xs:documentation>State or Territory</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="postcode">
<xs:annotation>
<xs:documentation>postcode</xs:documentation>
</xs:annotation>
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="[0-9]{4}"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element minOccurs="0" name="unstructuredAddressLine1" type="xs:string">
<xs:annotation>
<xs:documentation>Unstructured address line 1</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="unstructuredAddressLine2" type="xs:string">
<xs:annotation>
<xs:documentation>Unstructured address line 2</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="unstructuredAddressLine3" type="xs:string">
<xs:annotation>
<xs:documentation>Unstructured address line 3</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="unstructuredAddressLine4" type="xs:string">
<xs:annotation>
<xs:documentation>Unstructured address line 4</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="countryNameCode" type="xs:string">
<xs:annotation>
<xs:documentation>Country Name</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="locationDescriptor" type="xs:string">
<xs:annotation>
<xs:documentation>Description of location (eg "OFF PRINCESS ST")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="deliveryPointIdentifier">
<xs:annotation>
<xs:documentation>Australia Post's Delivery Point Identifier or DPID</xs:documentation>
</xs:annotation>
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="[0-9]{8}"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element minOccurs="0" name="geoFeature" type="xs:string">
<xs:annotation>
<xs:documentation>
Type of geographic feature (eg "Property Centroid")
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoDatumCode" type="xs:string">
<xs:annotation>
<xs:documentation>
Geographic datum and/or coordinate reference system (eg "GDA94", "MGA50", "EPSG:4326")
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoVerticalDatumCode" type="xs:string">
<xs:annotation>
<xs:documentation>Reference system for height (eg "AHD71")</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoNorthSouthCoordinate" type="xs:decimal">
<xs:annotation>
<xs:documentation>Coordinate value (eg latitude or northing)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoEastWestCoordinate" type="xs:decimal">
<xs:annotation>
<xs:documentation>Coordinate value (eg longitude or easting)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoHeight" type="xs:decimal">
<xs:annotation>
<xs:documentation>Height of address in metres</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoPositionalUncertainty" type="xs:decimal">
<xs:annotation>
<xs:documentation>Address positional uncertainty</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="geoContainment" type="xs:string">
<xs:annotation>
<xs:documentation>
Whether the coordinate is inside the address boundary
</xs:documentation>
</xs:annotation>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="notes">
<xs:annotation>
<xs:documentation>
The Notes Object allows the NAMF Web Service to provide additional information as name-value pairs.
</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" name="note">
<xs:annotation>
<xs:documentation>
A Note Object has a name as an attribute and a value.
</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="priority" type="priorityValue"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="error">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="code" type="xs:string"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="response">
<xs:annotation>
<xs:documentation>
A Response Object is created for each Request Object.
</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="responseResult">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" ref="address"/>
<xs:element minOccurs="0" ref="attributes"/>
<xs:element minOccurs="0" ref="notes"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element minOccurs="0" maxOccurs="unbounded" ref="callVersions"/>
<xs:element minOccurs="0" ref="notes"/>
<xs:element name="status" type="statusValue"/>
<xs:element maxOccurs="unbounded" minOccurs="0" ref="error"/>
</xs:sequence>
<xs:attribute name="id" type="xs:string"/>
</xs:complexType>
</xs:element>
<xs:simpleType name="CertaintyValue">
<xs:annotation>
<xs:documentation>Acceptable range of Certainty values</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:enumeration value="full"/>
<xs:enumeration value="partial"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="priorityValue">
<xs:annotation>
<xs:documentation>Acceptable range of priorities</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:enumeration value="CRITICAL"/>
<xs:enumeration value="WARNING"/>
<xs:enumeration value="INFO"/>
<xs:enumeration value="DEBUG"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="statusValue">
<xs:annotation>
<xs:documentation>Acceptable range of status values</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:enumeration value="OK"/>
<xs:enumeration value="ERROR"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="notificationTypeValue">
<xs:annotation>
<xs:documentation>
Acceptable range of notificationType values. 'U_ATTRIB_ONLY' was previously 'D_ATTRIB_ONLY'. 'U_GEO_ONLY' was previously 'D_GEO_ONLY'.
</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:enumeration value="I_INSERT"/>
<xs:enumeration value="U_ATTRIB_GEO"/>
<xs:enumeration value="X_COMMENT"/>
<xs:enumeration value="I_ALIAS"/>
<xs:enumeration value="D_GREENSPACE"/>
<xs:enumeration value="D_ROAD_RESERVE"/>
<xs:enumeration value="D_NOT_EXISTS"/>
<xs:enumeration value="U_ATTRIB_ONLY"/>
<xs:enumeration value="U_GEO_ONLY"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="addressStatusValue">
<xs:annotation>
<xs:documentation>
Acceptable range of address status values OFF - Official Address VAL - Valid Alias INV - Invalid Alias OBS - Obsolete Address
</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:enumeration value="OFF"/>
<xs:enumeration value="VAL"/>
<xs:enumeration value="INV"/>
<xs:enumeration value="OBS"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="stateTerritory">
<xs:annotation>
<xs:documentation>Acceptable range of state/territory values</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:enumeration value="AAT"/>
<xs:enumeration value="ACT"/>
<xs:enumeration value="NSW"/>
<xs:enumeration value="NT"/>
<xs:enumeration value="OT"/>
<xs:enumeration value="QLD"/>
<xs:enumeration value="SA"/>
<xs:enumeration value="TAS"/>
<xs:enumeration value="VIC"/>
<xs:enumeration value="WA"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="positiveInteger">
<xs:annotation>
<xs:documentation>Acceptable range of positive integers</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:pattern value="[0-9]+"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>
```

**Output of python -mzeep <URL>:**
Prefixes:
     ns0: http://ws.namf09.anzlic.org.au
     ns1: http://namf09.anzlic.org.au
     xsd: http://www.w3.org/2001/XMLSchema

Global elements:
     ns1:address(addressIdentifier: xsd:string, status: xsd:addressStatusValue, complexUnitType: xsd:string, complexUnitIdentifier: xsd:string, complexLevelType: xsd:string, complexLevelNumber: xsd:string, complexStreetNumber1: xsd:string, complexStreetNumber2: xsd:string, complexStreetName: xsd:string, complexStreetType: xsd:string, complexStreetSuffix: xsd:string, siteName: xsd:string, lotIdentifier: xsd:string, cadastralIdentifier: xsd:string, streetNumber1: xsd:string, streetNumber2: xsd:string, streetName: xsd:string, streetType: xsd:string, streetSuffix: xsd:string, postalDeliveryTypeCode: xsd:string, postalDeliveryIdentifier: xsd:string, localityName: xsd:string, stateTerritory: xsd:string, postcode: xsd:postcode, unstructuredAddressLine1: xsd:string, unstructuredAddressLine2: xsd:string, unstructuredAddressLine3: xsd:string, unstructuredAddressLine4: xsd:string, countryNameCode: xsd:string, locationDescriptor: xsd:string, deliveryPointIdentifier: xsd:deliveryPointIdentifier, geoFeature: xsd:string, geoDatumCode: xsd:string, geoVerticalDatumCode: xsd:string, geoNorthSouthCoordinate: xsd:decimal, geoEastWestCoordinate: xsd:decimal, geoHeight: xsd:decimal, geoPositionalUncertainty: xsd:decimal, geoContainment: xsd:string)
     ns1:attribute(attributeValue: xsd:string, attribute: attribute(), name: xsd:string)
     ns1:attributes(attribute: attribute())
     ns1:callVersions(callVersion: {description: xsd:string, version: xsd:string, features: features(), attributes: attributes()}[], name: xsd:string)
     ns1:error(xsd:string, code: xsd:string)
     ns0:execute(requests: requests())
     ns0:executeResponse(responses: responses())
     ns1:feature(featureValue: xsd:string, feature: feature(), name: xsd:string)
     ns1:features(feature: feature())
     ns1:notes(note: {xsd:string, name: xsd:string, priority: xsd:priorityValue}[])
     ns1:requests(authentication: {username: xsd:string, password: xsd:string}, features: features(), request: {features: features(), address: address(), attributes: attributes(), id: xsd:string, name: xsd:string}[], id: xsd:string, version: xsd:string)
     ns1:response(responseResult: {address: address(), attributes: attributes(), notes: notes()}[], callVersions: callVersions(), notes: notes(), status: xsd:statusValue, error: error(), id: xsd:string)
     ns1:responses(notes: notes(), result: {attributes: attributes(), status: xsd:statusValue, completed: xsd:boolean, hasErrorsInResponseElements: xsd:boolean}, error: error(), response: response(), id: xsd:string)

Global types:
     ns1:CertaintyValue(value)
     ns1:addressStatusValue(value)
     ns1:notificationTypeValue(value)
     ns1:positiveInteger(value)
     ns1:priorityValue(value)
     ns1:stateTerritory(value)
     ns1:statusValue(value)
     ns0:execute(requests: requests())
     ns0:executeResponse(responses: responses())

Bindings:
     Soap11Binding: {http://ws.namf09.anzlic.org.au}NCSPortBinding

Service: EngineService
     Port: NCSPort (Soap11Binding: {http://ws.namf09.anzlic.org.au}NCSPortBinding)
         Operations:
            execute(requests: requests()) -> notes: notes(), result: {attributes: attributes(), status: xsd:statusValue, completed: xsd:boolean, hasErrorsInResponseElements: xsd:boolean}, error: error(), response: response(), id: psd:string

**Code:**
```
from zeep import Client
import ssl
import See you soon!
import logging.config

if hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context

client = Client('<URL>')

logging.config.dictConfig({
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(name)s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'zeep.transports': {
            'level': 'DEBUG',
            'propagate': True,
            'handlers': ['console'],
        },
    }
})        

add = client.get_element('ns1:address')
address = add(unstructuredAddressLine1='1 broad pl kambah act 2902');


feat2 = client.get_element('ns1:feature')
feature2 = feat2(name='name', featureValue='PSMA:baseline_transaction')

feat3 = client.get_element('ns1:feature')
feature3 = feat3(name='parameters')

feat1 = client.get_element('ns1:feature')
feature1 = feat1(name='workflow', feature=[feature2, feature3])

feats = client.get_element('ns1:features')
features = feats(feature=feature1)

attrs = client.get_element('ns1:attributes')
attributes = attrs()

reqs = client.get_element('ns1:requests')
requests = reqs(authentication={
        'username': 'username', 
        'password': 'password',
        }, request=[{'features': features, 'address': address, 'attributes': attributes, 'name': 'executeWorkflow', 'id': '1.0'}], id='1.0', version='1.0')

print requests

responses = client.get_element('ns1:responses')
try:
    responses = client.service.execute(requests)
except:
    print 'dang call'
```

**Comment by mcordes** [comment]
Here's a quick script to reproduce the issue with the latest (0.14) release.

    from zeep import Client
    from zeep.transports import Transport

    class FakeResponse(object):
        status_code=200
        content="""<?xml version='1.0' encoding='UTF-8'?><S:Envelope     xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="http://axes.alldata.net/web-services/sales"><S:Body><ns0:sales36Response></ns0:sales36Response></S:Body></S:Envelope>"""

    class NoopTransport(Transport):
        def post(self, address, message, headers):
            print('request: {}'.format(message))
            return FakeResponse

    url = 'https://retailuat.alldata.net/axes103/web-services/sales3x?wsdl'
    client = Client(url, transport=NoopTransport())

    # First attempt, this doesn't work. Version is an attribute on this XSD object, 
    # When invoked like this it doesn't get added to the outgoing request
    print("** Attempt 1")
    client.service.sales36({'version': '3.6.7', 'authCode': '1234'})

    # Second attempt, this does work. In this scenario the version attribute does 
    # find its way into the request message
    request = client.get_type('ns1:salesRequest30')()
    request.version = '3.6.7'
    request.authCode = '1234'
    print("** Attempt 2")
    client.service.sales36(request)

And here are the results. You'll notice that the first one (using a dictionary as the object) ends up dropping the 'version' attribute. It's not in the request.  The second one - using the actual XSD object includes the version attribute and works as expected. 


** Attempt 1

    request: <?xml version='1.0' encoding='utf-8'?>
    <soap-env:Envelope xmlns:ns1="http://axes.alldata.net/web-services/sales" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
      <soap-env:Body>
        <ns1:sales36>
          <request>
            <authCode>1234</authCode>
          </request>
        </ns1:sales36>
      </soap-env:Body>
    </soap-env:Envelope>

** Attempt 2

    request: <?xml version='1.0' encoding='utf-8'?>
    <soap-env:Envelope xmlns:ns1="http://axes.alldata.net/web-services/sales" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
      <soap-env:Body>
        <ns1:sales36>
          <request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.6.7" xsi:type="ns1:salesRequest30">
            <authCode>1234</authCode>
          </request>
        </ns1:sales36>
      </soap-env:Body>
    </soap-env:Envelope>


I hope that's helpful. Please let me know if there's anything else I can elaborate one. 

Once again, I really appreciated this library. Thanks for working on this.

**Comment by mvantellingen** [comment]
I think this should be fixed with dc373764db6cb5b8393820786584d00880e2f9a2
Let me know :-)

**Comment by mcordes** [comment]
@mvantellingen Sorry for the very slow reply, but this still doesn't appear to be working. here's my updated test case:

```
from zeep import Client
from zeep.transports import Transport

class FakeResponse(object):
    status_code=200
    content="""<?xml version='1.0' encoding='UTF-8'?><S:Envelope     xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="http://axes.alldata.net/web-services/sales"><S:Body><ns0:sales36Response></ns0:sales36Response></S:Body></S:Envelope>"""
    headers={}

class NoopTransport(Transport):
    def post(self, address, message, headers):
        print('request: {}'.format(message))
        return FakeResponse

url = 'https://retailuat.alldata.net/axes103/web-services/sales3x?wsdl'
client = Client(url, transport=NoopTransport())

# First attempt, this doesn't work. Version is an attribute on this XSD object, 
# When invoked like this it doesn't get added to the outgoing request
print("** Attempt 1")
client.service.sales36({'version': '3.6.7', 'authCode': '1234'})

# Second attempt, this does work. In this scenario the version attribute does 
# find its way into the request message
request = client.get_type('ns1:salesRequest30')()
request.version = '3.6.7'
request.authCode = '1234'
print("** Attempt 2")
client.service.sales36(request)
```

And here are the results. Note the *version* attribute is still missing from _Attempt 1_, the one built from a dictionary and not from the xsd object. _Attempt 2_ correctly includes this attribute.


** Attempt 1
request: 

```
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns1="http://axes.alldata.net/web-services/sales" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns1:sales36>
      <request>
        <authCode>1234</authCode>
      </request>
    </ns1:sales36>
  </soap-env:Body>
</soap-env:Envelope>
```

** Attempt 2
request:

```
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns1="http://axes.alldata.net/web-services/sales" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns1:sales36>
      <request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.6.7" xsi:type="ns1:salesRequest30">
        <authCode>1234</authCode>
      </request>
    </ns1:sales36>
  </soap-env:Body>
</soap-env:Envelope>
```

**Comment by mvantellingen** [comment]
I get no content back from https://retailuat.alldata.net/axes103/web-services/sales3x?wsdl ?

**Comment by mcordes** [comment]
@mvantellingen  It seems to be sporadically working I'm afraid. It's up right now.

**Comment by mvantellingen** [comment]
Hi @mcordes, I'd really like to solve this issue, but unfortunately I still can't download the wsdl (tried various times). Do you have the file available somewhere?

**Comment by mvantellingen** [comment]
Hi @mcordes, sorry but i'll have to close this issue. Since this is a volunteer project I try to keep it from taking too much of my spare time. If you have more information and you still want to help me out fixing this, then please create a script for which exposes the problem. See http://docs.python-zeep.org/en/master/reporting_bugs.html for examples
