### ISSUE TITLE
python3 -mzeep <url to wsdl> fails with "AttributeError: 'Schema' object has no attribute 'add_schema'"

### ISSUE THREAD

**Issue by elad661** [mvantellingen/python-zeep#179]
To reproduce:

1. download this zip file and extract it http://media.mot.gov.il/PDF/HE_TRAFFIC_PUBLIC/ANHAYIOT/SIRI-ISRAEL.zip
2. In the extracted directory, type `python3 -mzeep siri_wsConsumer.wsdl`

The result is:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/zeep/__main__.py", line 80, in <module>
    main(args)
  File "/usr/lib/python3.5/site-packages/zeep/__main__.py", line 69, in main
    client = Client(args.wsdl_file, transport=transport)
  File "/usr/lib/python3.5/site-packages/zeep/client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/usr/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/usr/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 152, in __init__
    self.parse_imports(doc)
  File "/usr/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 231, in parse_imports
    self.types.add_schema(document, location)
AttributeError: 'Schema' object has no attribute 'add_schema'
```

running zeep 0.15.0, installed via pip.

**Comment by mvantellingen** [comment]
oops, should be fixed now

**Comment by mvantellingen** [comment]
Just released 0.16 with a fix for this, please let me know if you run into any issues

**Comment by elad661** [comment]
Thanks. This wsdl still won't load (with all kind of file not found errors). I don't know if it's a problem with zeep or with this archive though.

I shuffled the files around a bit to get around the file not found errors, like so:

```bash
mkdir foo
mv *xsd foo/
mv *wsdl foo/
mv siri/ foo/
cp siri/* foo/
mv datex2 foo/
cd foo/
python3 -mzeep siri_wsConsumer.wsdl
```

And now I'm getting a different error message: 

```
Prefixes:
     xsd: http://www.w3.org/2001/XMLSchema
     ns2: http://www.ifopt.org.uk/ifopt
     ns4: http://datex2.eu/schema/1_0/1_0
     ns3: http://www.ifopt.org.uk/acsb
     ns0: http://www.siri.org.uk/siri
     ns1: http://www.w3.org/XML/1998/namespace

Global elements:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 50, in __get__
    return obj_dict[name]
KeyError: 'elements_nested'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 50, in __get__
    return obj_dict[name]
KeyError: 'elements'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 50, in __get__
    return obj_dict[name]
KeyError: 'elements'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 50, in __get__
    return obj_dict[name]
KeyError: 'elements_nested'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/__main__.py", line 85, in <module>
    main(args)
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/__main__.py", line 80, in main
    client.wsdl.dump()
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/wsdl/wsdl.py", line 83, in dump
    for elm_obj in sorted(self.types.elements, key=lambda k: six.text_type(k)):
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/wsdl/wsdl.py", line 83, in <lambda>
    for elm_obj in sorted(self.types.elements, key=lambda k: six.text_type(k)):
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/elements.py", line 199, in __str__
    return '%s(%s)' % (self.name, self.type.signature())
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/types.py", line 405, in signature
    part = element.signature(depth)
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/indicators.py", line 202, in signature
    for name, element in self.elements_nested:
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/indicators.py", line 72, in elements_nested
    for sub_name, sub_elm in elm.elements:
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/indicators.py", line 485, in elements
    return self.child.elements
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/indicators.py", line 53, in elements
    for name, elm in self.elements_nested:
  File "/usr/lib/python3.5/site-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/usr/lib/python3.5/site-packages/zeep-0.16.0-py3.5.egg/zeep/xsd/indicators.py", line 78, in elements_nested
    name = generator_2.create_name(elm.name)
AttributeError: 'RefElement' object has no attribute 'name'
```

(I omitted the ``ZeepWarning: Skipping import of schema`` warnings from this output, because there are a lot of them and they just say some of the schemas were imported in multiple files and therefor skipped)

This looks like a completely different issue though, so if you want I can file it in a new issue.
