### ISSUE TITLE
Please publish the sign key of zeep 2.5.0

### ISSUE THREAD

**Issue by mbehrle** [mvantellingen/python-zeep#718]
Dear Maintainer,

I couldn't find the signing key for 
https://pypi.python.org/packages/66/84/b3332635bdc649706fb26190f667fd656a1a7eb3c95201c1e3a58d853827/zeep-2.5.0.tar.gz.asc
on any public keyserver. Thus there is no possibility to check back the signer of the package, required e.g. in Debian packaging.

Could you please submit the key on a public keyserver?

Thanks,
Mathias Behrle

**Comment by mvantellingen** [comment]
Should be fixed now, thanks

**Comment by mbehrle** [comment]
Hi,
uploads to a keyserver should have propagated meanwhile to the mirrors, but I still can't find the appropriate key.

$ gpg -v zeep-2.5.0.tar.gz.asc
...
gpg: die unterzeichneten Daten sind wohl in 'zeep-2.5.0.tar.gz'
gpg: Signatur vom Sa 06 Jan 2018 15:58:33 CET
gpg:                mittels RSA-Schlüssel B58A7FFB4E04A54B4EBF01C7B25EF97F6B8CF4C2
gpg: Signatur kann nicht geprüft werden: Kein öffentlicher Schlüssel

$ gpg --search-keys van tellingen
gpg: data source: http://176.9.31.215:11371
(1)     Michael van Tellingen <michaelvantellingen@gmail.com>
          2048 bit RSA key E5A8120B3DEF67BF, erzeugt: 2017-04-22, verfällt: 2019-04-22
(2)     Michael van Tellingen <michael@mvantellingen.nl>
          4096 bit RSA key 96B67042ABC44F77, erzeugt: 2016-04-05

$ gpg --search-keys 0xB58A7FFB4E04A54B4EBF01C7B25EF97F6B8CF4C2
gpg: error searching keyserver: Keine Daten
