### ISSUE TITLE
KeyError: No such type

### ISSUE THREAD

**Issue by LiveStalker** [mvantellingen/python-zeep#79]
Hello. I try work with some SOAP service (WSDL in attachment) and get error.
Test code:
```
from zeep import Client
from zeep.transports import Transport
from zeep.wsse.username import UsernameToken

transport = Transport(verify=False)
client = Client(
    'my url',
    wsse=UsernameToken('username', 'password'),
    transport=transport)
```

```
Traceback (most recent call last):
  File "C:/projects/iidk/wsdl3.py", line 9, in <module>
    transport=transport)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\wsdl\wsdl.py", line 154, in __init__
    self.schema = self.parse_types(doc)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\wsdl\wsdl.py", line 331, in parse_types
    self.wsdl._parser_context, self.location)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\xsd\schema.py", line 51, in __init__
    schema.resolve()
  File "C:\develop\ve\broker27\lib\site-packages\zeep\xsd\schema.py", line 86, in resolve
    new = type_.resolve(self)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\xsd\types.py", line 189, in resolve
    xsd_type = elm.resolve(schema)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\xsd\types.py", line 40, in resolve
    retval = schema.get_type(self.qname)
  File "C:\develop\ve\broker27\lib\site-packages\zeep\xsd\schema.py", line 128, in get_type
    name.text, ', '.join(self._types)))
KeyError: u"No such type: u'{http://schemas.datacontract.org/2004/07/System}Exception' (Only have {http://schemas.datacontract.org/2004/07/System.Net.Sockets}AddressFamily, {http://schemas.datacontract.org/2004/07/System.Net.Sockets}SocketException)"
```

Please help.

[LNetworkService.svc.zip](https://github.com/mvantellingen/python-zeep/files/317071/LNetworkService.svc.zip)

**Comment by jmccarrell** [comment]
I am getting a similar error -- in terms of the stack trace if not the exact error message -- trying to parse a fairly complex WSDL.  The wsdl itself apparently is valid as apache cxf validates it just fine.  However, zeep gives KeyError: no such element:

```
>>> client = zeep.Client(wsdl=end_point + '?wsdl', transport=transport_with_basic_auth)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 155, in __init__
    self.messages = self.parse_messages(doc)
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 347, in parse_messages
    msg = definitions.AbstractMessage.parse(self, msg_node)
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 61, in parse
    part_element = definitions.schema.get_element(part_element)
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/xsd/schema.py", line 136, in get_element
    return self._imports[name.namespace].get_element(name)
  File "/Users/jeff/tmp/venvs/zeeptest/lib/python3.5/site-packages/zeep/xsd/schema.py", line 140, in get_element
    name.text, ', '.join(self._elements), self))
KeyError: "No such element: '{http://www.boe.ca.gov/ws/002}BOEResponseHeader' (Only have {http://www.boe.ca.gov/ws/002}EchoResponse) (from: <Schema(location='https://testeservices.boe.ca.gov/websvcs/pvt/svs/version002?wsdl&resource=../../../002/CABOE/interfaces/EchoResponse.xsd', is_empty=False)>)"
```

The issue appears to me to be around namespace management of imports.

**Comment by Tset-Noitamotua** [comment]
same error here:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\wsdl\wsdl.py", line 152, in __init__
    self.parse_imports(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\wsdl\wsdl.py", line 243, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\wsdl\wsdl.py", line 154, in __init__
    self.schema = self.parse_types(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\wsdl\wsdl.py", line 287, in parse_types
    self.wsdl._parser_context, self.location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\xsd\schema.py", line 52, in __init__
    self.resolve()
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\xsd\schema.py", line 91, in resolve
    element.resolve_type(self)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\xsd\elements.py", line 123, in resolve_type
    self.type = self.type.resolve(schema)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\xsd\types.py", line 40, in resolve
    retval = schema.get_type(self.qname)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\xsd\schema.py", line 124, in get_type
    return self._imports[name.namespace].get_type(name)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep\xsd\schema.py", line 128, in get_type
    name.text, ', '.join(self._types)))
KeyError: u"No such type: u'{http://com/company/foo/bar/boo}ServiceMethodInput' (Only have {http://com/company/foo/bar/boo}SomethingElse)"
```

Unfortunately I can´t expose the WSDL file here but the structure looks something like this:

```xml
<wsdl:definitions xmlns:Port_0="http://blablabla"   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://blablabla/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="blablabla_service" targetNamespace="blablabla/Binding">
    <wsdl:import location="Service.wsdl" namespace="http://blablabla"></wsdl:import>
    <wsdl:binding name="blablabla" type="Port_0:Servie">...</wsdl:binding>
    <wsdl:service name="blablabla_Service">
        <wsdl:port binding="this:blablabla" name="blablalba">
            <soap:address location="http://blabla"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
```

**Comment by mvantellingen** [comment]
So I found out that there was some logic error with resolve types. This happens if types need to be resolve through multiple xml schema's. Should be fixed for @LiveStalker test. If the other issues are not resolved by this then it would be nice to get separate issues for that

**Comment by koyeung** [comment]
Similar to above case (`KeyError: "No such element:`). it could be loaded using SOAPClient [TokenManagement_1](http://www.soapclient.com/soapclient?template=%2Fclientform.html&fn=soapform&SoapTemplate=%2FSoapResult.html&SoapWSDL=http%3A%2F%2Fapi.rkd.reuters.com%2Fschemas%2Fwsdl%2FTokenManagement_1_HttpAndRKDToken.wsdl&_ArraySize=2)

May you help to have a look? thanks

```python
from zeep import Client
client = Client('http://api.rkd.reuters.com/schemas/wsdl/TokenManagement_1_HttpAndRKDToken.wsdl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/pyenv/lib/python3.5/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/private/tmp/pyenv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/private/tmp/pyenv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 155, in __init__
    self.messages = self.parse_messages(doc)
  File "/private/tmp/pyenv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 347, in parse_messages
    msg = definitions.AbstractMessage.parse(self, msg_node)
  File "/private/tmp/pyenv/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 61, in parse
    part_element = definitions.schema.get_element(part_element)
  File "/private/tmp/pyenv/lib/python3.5/site-packages/zeep/xsd/schema.py", line 140, in get_element
    name.text, ', '.join(self._elements), self))
KeyError: "No such element: '{http://www.reuters.com/ns/2006/05/01/webservices/rkd/Common_1}Authorization' (Only have ) (from: <Schema(location='http://api.rkd.reuters.com/schemas/wsdl/TokenManagement_1_HttpAndRKDToken.wsdl', is_empty=False)>)"
```

**Comment by mvantellingen** [comment]
Did you try the master branch?

**Comment by koyeung** [comment]
Hi,
Previously, I tried with 0.9.1.
Then try with master branch:
(using Python3.5.1)
```
$ pip install git+https://github.com/mvantellingen/python-zeep.git@master
Collecting git+https://github.com/mvantellingen/python-zeep.git@master
  Cloning https://github.com/mvantellingen/python-zeep.git (to master) to /var/folders/kj/2vsw1hc945v5m3bjk5xj0rxw0000gp/T/pip-goylwxfo-build
Collecting appdirs>=1.4.0 (from zeep==0.10.0.dev0)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
...
```

and I got same result:

```python
from zeep import Client
client = Client('http://api.rkd.reuters.com/schemas/wsdl/TokenManagement_1_HttpAndRKDToken.wsdl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/koyeung/20160619/testzeep2/lib/python3.5/site-packages/zeep/client.py", line 48, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/private/tmp/koyeung/20160619/testzeep2/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/private/tmp/koyeung/20160619/testzeep2/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 155, in __init__
    self.messages = self.parse_messages(doc)
  File "/private/tmp/koyeung/20160619/testzeep2/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 347, in parse_messages
    msg = definitions.AbstractMessage.parse(self, msg_node)
  File "/private/tmp/koyeung/20160619/testzeep2/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 61, in parse
    part_element = definitions.schema.get_element(part_element)
  File "/private/tmp/koyeung/20160619/testzeep2/lib/python3.5/site-packages/zeep/xsd/schema.py", line 142, in get_element
    name.text, ', '.join(self._elements), self))
KeyError: "No such element: '{http://www.reuters.com/ns/2006/05/01/webservices/rkd/Common_1}Authorization' (Only have ) (from: <Schema(location='http://api.rkd.reuters.com/schemas/wsdl/TokenManagement_1_HttpAndRKDToken.wsdl', tns=http://www.reuters.com/ns/2006/05/01/webservices/rkd/TokenManagement_1/HttpAndRKDToken/Imports, is_empty=False)>)"
```

**Comment by mvantellingen** [comment]
It would be cool if you all could try #87. It should solve most of the issues reported here. The issue was that only elements and types on the root schema documents were available to the wsdl, however all global elements/types should be available.

I need to do some more cleanup and add some regressions tests but please let me know if it solves it.

**Comment by mvantellingen** [comment]
So i've just merged the refactor-xsd-lookup branch which should close this issue. If there are still errors but the stacktraces differ then please create separate issues for this.

Thanks :)

**Comment by koyeung** [comment]
it works now. thanks!

**Comment by jmccarrell** [comment]
I think zeep is getting farther parsing the wsdl I am working with, but KeyError is still thrown.  See issue #90

**Comment by Tset-Noitamotua** [comment]
I still have issue to create a client. See #96
